spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nonogram
    username: postgres
    password: qwe123
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
      javax:
        persistence:
          validation:
            mode: none